### ISSUE TITLE
This solution seems to work only for 10minutes

### ISSUE THREAD

**Issue by madhavanmalolan** [sweta20/hotstar-linux#4]
The response from the API mentioned in content.js has an expiry time that is 10minutes from start.
I have to reload every 10 minutes, turned out to be a hassle.

**Comment by madhavanmalolan** [comment]
I think i have a working solution using Flowplayer
I have hosted it at : http://playhotstar.madhavanmalolan.com

**Comment by anomitra** [comment]
@madhavanmalolan I think your solution, along with all others will have stopped working now. They have disallowed cross-origin requests in the server hosting the M3U8 URLs  :disappointed:

**Comment by madhavanmalolan** [comment]
Surprisingly not. It is an unprotected API with links to the stream on their CDN.


On Sep 9, 2017 8:37 PM, Anomitra Saha <notifications@github.com> wrote:

@madhavanmalolan I think your solution, along with all others will have stopped working now. They have disallowed cross-origin requests in the server hosting the M3U8 URLs 😞

**Comment by anomitra** [comment]
Yes, another person working on this also told me so. Must be a local
problem for me. I'll check it out.

On 10 Sep 2017 1:03 am, "madhavanmalolan" <notifications@github.com> wrote:

Surprisingly not. It is an unprotected API with links to the stream on
their CDN.


On Sep 9, 2017 8:37 PM, Anomitra Saha <notifications@github.com> wrote:

@madhavanmalolan I think your solution, along with all others will have
stopped working now. They have disallowed cross-origin requests in the
server hosting the M3U8 URLs 😞

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/sweta20/hotstar-linux/issues/4#issuecomment-328298862>,
or mute the thread

**Comment by sweta20** [comment]
It might have happened. I wrote it around 7 months back and have not been maintaining it.
